
os: osx
osx_image: xcode7.3

env:
  R_VERSION: 3.6.3
  R_HOME: /Library/Frameworks/R.framework/Resources

install:
  - curl -o R.pkg https://cran.r-project.org/bin/macosx/R-$R_VERSION.pkg
  - sudo installer -package R.pkg -target /

before_script:
  - sed -i.bak 's/-isysroot /-I/g' $R_HOME/etc/Makeconf

script:
  - git submodule update --init --recursive
  - R CMD INSTALL --build Rcpp

after_success:
  - brew install marcelomazza/homebrew-curl-libssh2/curl
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
  - /usr/local/opt/curl/bin/curl
         --ftp-create-dirs
         --insecure
         --key /tmp/sftp_rsa
         -T *.tgz
         sftp://${SFTP_USER}@jamovi.org/home/${SFTP_USER}/jamovi.org/downloads/
